name: Python Application

on:
  push:
    branches: [ "main","i200983" ]
  pull_request:
    branches: [ "main","i200983" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: dvc setup
      run: |
        dvc --version
        dvc remote add -f myremote gdrive://1ZJZmaYaA77kOh0IdPIOzcRQDEGwGnCJO
        dvc pull
        python random_data.py
        dvc add data/dummy_sensor_data.csv
        'dvc push -r myremote'
    - name: Execute Mlflow training and Data Gather
      run: python main.py
      
