name: Python Application

on:
  push:
    branches: [ "main","i200983" ]
  pull_request:
    branches: [ "main","i200983" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Setup DVC
      uses: iterative/setup-dvc@v1
    
    - name: Setup Google Drive credentials
      env:
        GDRIVE_CLIENT_ID: ${{ secrets.GDRIVE_CLIENT_ID }}
        GDRIVE_CLIENT_SECRET: ${{ secrets.GDRIVE_LINK}}
        GDRIVE_SERVICE_ACCOUNT_JSON: ${{ secrets.GDRIVE_API }}
      run: |
        echo "$GDRIVE_SERVICE_ACCOUNT_JSON" > dvc-remote-connections.json
        dvc remote modify storage gdrive_client_id $GDRIVE_CLIENT_ID
        dvc remote modify storage gdrive_client_secret $GDRIVE_CLIENT_SECRET
        dvc remote modify storage gdrive_service_account_json_file_path dvc-remote-connections.json

    - name: Pull Data from DVC
      run: |
        dvc pull
    - name: Add More Data to DVC    
      run: |
        python random_data.py
        dvc add dummy_sensor_data.csv
    - name: Push data back to gdrive
      run: 'dvc push -r storage'
    - name: Execute Mlflow training and Data Gather
      run: |
        nohup mlflow ui --backend-store-uri ./mlruns --port 5000 --host fahadkamran.xyz &
        python main.py
      
